---
- name: Gather subscription data
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get K8S cluster info
      kubernetes.core.k8s_cluster_info:
      register: ocp_version
    - name: Save cluster version
      ansible.builtin.set_fact:
        k8s_cluster_version: "{{ ocp_version.version.server.kubernetes }}"
    - name: Get OpenShift cluster info
      kubernetes.core.k8s_info:
        api_version: "config.openshift.io/v1"
        kind: ClusterVersion
        name: version
      register: openshift_cluster_version
    - name: Get PackageManifests
      kubernetes.core.k8s_info:
        api_version: "packages.operators.coreos.com/v1"
        kind: PackageManifest
      register: package_manifest_list
    - name: Filter package_manifest_list
      ansible.builtin.set_fact:
        manifest_list: "{{ package_manifest_list.resources |
                           selectattr('status.packageName', 'in', packages | list) }}"
      when: packages | default([]) | length > 0
    - name: Make manifest_list when no packages defined
      ansible.builtin.set_fact:
        manifest_list: "{{ package_manifest_list.resources | list }}"
      when: packages | default([]) | length == 0
    - name: Get subscription data from OpenShift
      ansible.builtin.set_fact:
        openshift_sub_info: "{{ manifest_list |
                                map(attribute='status') |
                                selectattr('catalogSource', 'in', '[' + catalog_source + ']') |
                                list }}"
    - name: Execute operator_install.yml for each opernshift_sub_info
      ansible.builtin.include_tasks: operator_install.yml
      vars:
        install_operands: install_operands | default(false)
      loop: "{{ openshift_sub_info }}"
      loop_control:
        loop_var: manifest_data
