---
- name: Gather "inventory" of packages
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Only gather date_time to facts
      ansible.builtin.setup:
        filter:
          - ansible_date_time
    - name: Set current date to stats
      ansible.builtin.set_stats:
        data:
          current_date: "{{ ansible_date_time.date }}"
    - name: Get K8S cluster info
      kubernetes.core.k8s_cluster_info:
      register: ocp_version
      no_log: true
    - name: Save cluster version
      ansible.builtin.set_stats:
        data:
          k8s_cluster_version: "{{ ocp_version.version.server.kubernetes }}"
    - name: Get OpenShift cluster info
      kubernetes.core.k8s_info:
        api_version: "config.openshift.io/v1"
        kind: ClusterVersion
        name: version
      register: openshift_cluster_version
      failed_when: >
        (openshift_cluster_version.resources[0] is not defined) or
        (openshift_cluster_version.resources[0] == "")
    - name: Save OpenShift cluster info
      ansible.builtin.set_stats:
        data:
          openshift_cluster_version: "{{ openshift_cluster_version.resources[0].status.history[0].version }}"
    - name: Set cluster base URL
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: DNS
        name: cluster
      register: cluster_dns
    - name: Set fact
      ansible.builtin.set_fact:
        cluster_base_url: "{{ cluster_dns.resources[0].spec.baseDomain }}"
    - name: Build package "inventory"
      ansible.builtin.add_host:
        name: "{{ item.name }}"
        catalog_source: "{{ item.catalog_source }}"
        catalog_source_namespace: "{{ item.catalog_source_namespace }}"
        cluster_base_url: "{{ cluster_base_url }}"
        role_name_override: "{{ item.role_name_override | default(omit) }}"
        groups: "packages"
        ansible_ssh_host: localhost
        ansible_connection: local
      loop: "{{ packages }}"
      when: packages | default([]) | length > 0

- name: Run assessments
  hosts: packages
  gather_facts: false
  pre_tasks:
    - name: Cluster base url?
      ansible.builtin.debug:
        var: cluster_base_url
    - name: Alias inventory_hostname for easier readability
      ansible.builtin.set_fact:
        package: "{{ inventory_hostname }}"
        package_role: "{{ role_name_override | default(inventory_hostname | replace('-', '_')) }}"
    - name: Get PackageManifests
      kubernetes.core.k8s_info:
        api_version: "packages.operators.coreos.com/v1"
        kind: PackageManifest
        namespace: "{{ hostvars[package]['catalog_source_namespace'] }}"
        name: "{{ package }}"
        label_selectors:
          - "catalog = {{ hostvars[package]['catalog_source'] }}"
      register: package_manifest_data
      failed_when: >
        (package_manifest_data.resources | length == 0) or
        (package_manifest_data.resources[0].status is not defined)
    - name: Set package_manifest fact
      ansible.builtin.set_fact:
        package_manifest: "{{ package_manifest_data.resources[0].status.channels |
                              selectattr('name', 'eq', package_manifest_data.resources[0].status.defaultChannel) |
                              first }}"
        package_name: "{{ package_manifest_data.resources[0].status.packageName }}"
    - name: Generate namespace prefix
      ansible.builtin.set_fact:
        install_namespace_prefix: "{{ package_name | sha1 | truncate(8, False, '', 0) }}"
  roles:
    - role: fips_assessment
      install_mode: "OwnNamespace"
      install_namespace: "{{ [install_namespace_prefix, 'o'] | join('-') }}"
      target_namespace: "{{ [install_namespace_prefix, 'o'] | join('-') }}"
      when: >
        package_manifest.currentCSVDesc.installModes |
        selectattr('type', 'eq', 'OwnNamespace') |
        selectattr('supported', 'eq', true)
      tags:
        - ownnamespace
    - role: fips_assessment
      install_mode: "SingleNamespace"
      install_namespace: "{{ [install_namespace_prefix, 's'] | join('-') }}"
      target_namespace: "{{ [install_namespace_prefix, 's', 'ns1'] | join('-') }}"
      when: >
        package_manifest.currentCSVDesc.installModes |
        selectattr('type', 'eq', 'SingleNamespace') |
        selectattr('supported', 'eq', true)
      tags:
        - never
        - singlenamespace
    - role: fips_assessment
      install_mode: "MultiNamespace"
      install_namespace: "{{ [install_namespace_prefix, 'm'] | join('-') }}"
      target_namespace: "{{ [install_namespace_prefix, 'm', 'ns1'] | join('-') }}"
      when: >
        package_manifest.currentCSVDesc.installModes |
        selectattr('type', 'eq', 'MultiNamespace') |
        selectattr('supported', 'eq', true)
      tags:
        - never
        - multinamespace
    - role: fips_assessment
      install_mode: "AllNamespaces"
      install_namespace: "{{ [install_namespace_prefix, 'a'] | join('-') }}"
      target_namespace: "{{ [install_namespace_prefix, 'a', 'ns1'] | join('-') }}"
      when: >
        package_manifest.currentCSVDesc.installModes |
        selectattr('type', 'eq', 'AllNamespaces') |
        selectattr('supported', 'eq', true)
      tags:
        - never
        - allnamespaces
