---
# tasks file for fips_assessment
- name: Create install namespace
  ansible.builtin.include_role:
    role: k8s_namespace
  vars:
    k8s_namespace_namespace: "{{ fips_assessment_install_namespace }}"
    labels:
      - key: opdev
        value: opcap
      - key: opcap
        value: fips

- name: Create target namespace
  ansible.builtin.include_role:
    role: k8s_namespace
  vars:
    k8s_namespace_namespace: "{{ fips_assessment_target_namespace }}"
    labels:
      - key: opdev
        value: opcap
      - key: opcap
        value: fips

- name: Install operator
  ansible.builtin.include_role:
    name: operator
  vars:
    operator_role_mode: install
    operator_install_mode: "{{ fips_assessment_install_mode }}"
    operator_install_namespace: "{{ fips_assessment_install_namespace }}"
    operator_target_namespace: "{{ fips_assessment_target_namespace }}"

- name: Execute fips-assessment role
  ansible.builtin.include_role:
    name: "{{ package_role }}"
  vars:
    install_namespace: "{{ fips_assessment_install_namespace }}"
    target_namespace: "{{ fips_assessment_target_namespace }}"

- name: Create FIPS result
  ansible.builtin.set_fact:
    assessment_stat:
      result: "{{ assessment_result | default('result not reported') }}"
      package_name: "{{ package_name }}"
      install_type: "{{ fips_assessment_install_mode }}"

- name: Push FIPS stats
  ansible.builtin.set_stats:
    data:
      fips_assessments: "{{ omit if assessment_stat is not defined else [assessment_stat] }}"

- name: Clean up operator
  ansible.builtin.include_role:
    name: operator
  vars:
    operator_role_mode: cleanup
    operator_install_mode: "{{ fips_assessment_install_mode }}"
    operator_install_namespace: "{{ fips_assessment_install_namespace }}"
    operator_target_namespace: "{{ fips_assessment_target_namespace }}"
  when: cleanup | default(true)

- name: Clean up target namespace
  ansible.builtin.include_role:
    role: k8s_namespace
  vars:
    k8s_namespace_namespace: "{{ fips_assessment_target_namespace }}"
    k8s_namespace_state: absent
  when: cleanup | default(true)

- name: Clean up target namespace
  ansible.builtin.include_role:
    role: k8s_namespace
  vars:
    k8s_namespace_namespace: "{{ fips_assessment_install_namespace }}"
    k8s_namespace_state: absent
  when: cleanup | default(true)
